Added new debugging output to the UniConfDaemon, and modified it to use WvLogConsole. Also added the ability to mount multiple files at the start instead of just uniconf.ini
Using Debugging Output Level:

./uniconfdaemon -d [level]
level = Critical | Error | Warning | Notice | Info | Debug1 | Debug2 | Debug3 | Debug4 | Debug5

Usage of Debugging levels:
Critical:  Anything that will cause the daemon to die miserably.
Error:     Errors which are important, but may not cause us to crash and burn.
Warning:   Items which are suspect and should be looked into
Notice:    Currently not used.
Info:      Things like starting, saving, stopping.
Debug1:    To track program flow.  Method entrance/exit notifications
Debug2:    Supplies connection information immediately below method entrance notification where applicable
Debug3:    Supplies response information.

Debug4/5:  Use for whatever

BUGZID: 876


git-svn-id: file:///home/apenwarr/alumnit-svn/public/trunk@1513 6619c942-59fa-0310-bf43-a07aaa81d9ac